let ADMIN_TOKEN=null,ADMIN_EXP=0,EXP_TIMER=null;
const loader=document.getElementById("loader");
function showLoader(){if(loader)loader.style.display="block"}
function hideLoader(){if(loader)loader.style.display="none"}
function b64url(s){return s.replace(/-/g,"+").replace(/_/g,"/")}
function parseJWT(t){try{const p=t.split(".")[1];return JSON.parse(atob(b64url(p)))}catch{return {}}}
function clearTimer(){if(EXP_TIMER){clearTimeout(EXP_TIMER);EXP_TIMER=null}}
function scheduleExpiry(){clearTimer();const ms=Math.max(0,(ADMIN_EXP*1000)-Date.now());EXP_TIMER=setTimeout(()=>{logout()},ms)}
function saveToken(t){const d=parseJWT(t);ADMIN_TOKEN=t;ADMIN_EXP=d.exp||0;localStorage.setItem("admin_token",t);scheduleExpiry();const a=document.getElementById("tokenInfo");if(a)a.textContent="Sesión activa";const o=document.getElementById("btnLogout");if(o)o.classList.remove("hidden");const b=document.getElementById("loginBox");if(b)b.classList.add("hidden");const tabs=document.getElementById("tabs");if(tabs)tabs.classList.remove("hidden")}
function loadToken(){const t=localStorage.getItem("admin_token");if(!t)return;const d=parseJWT(t);if((d.exp||0)*1000>Date.now()){ADMIN_TOKEN=t;ADMIN_EXP=d.exp||0;scheduleExpiry();const a=document.getElementById("tokenInfo");if(a)a.textContent="Sesión activa";const o=document.getElementById("btnLogout");if(o)o.classList.remove("hidden");const b=document.getElementById("loginBox");if(b)b.classList.add("hidden");const tabs=document.getElementById("tabs");if(tabs)tabs.classList.remove("hidden")}else{localStorage.removeItem("admin_token")}}
function logout(){ADMIN_TOKEN=null;ADMIN_EXP=0;localStorage.removeItem("admin_token");clearTimer();const a=document.getElementById("tokenInfo");if(a)a.textContent="No autenticado";const o=document.getElementById("btnLogout");if(o)o.classList.add("hidden");const b=document.getElementById("loginBox");if(b)b.classList.remove("hidden");const tabs=document.getElementById("tabs");if(tabs)tabs.classList.add("hidden")}
async function fetchJSON(url,opts={}){const h=Object.assign({},opts.headers||{});if(ADMIN_TOKEN)h.Authorization="Bearer "+ADMIN_TOKEN;const r=await fetch(url,Object.assign({credentials:"include",headers:h},opts));if(r.status===401&&ADMIN_TOKEN){logout()}if(!r.ok)throw new Error(String(r.status));const ct=r.headers.get("content-type")||"";return ct.includes("application/json")?r.json():r.text()}
async function ensureTS(){if(window.__tsGate){showLoader();try{await window.__tsGate.ensure()}finally{hideLoader()}}}
async function login(){const pwd=document.getElementById("password").value||"";if(!pwd)return;showLoader();try{const d=await fetchJSON(API_URL+"/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:pwd})});saveToken(d.token)}catch{const m=document.getElementById("loginMsg");if(m)m.textContent="Error de login"}hideLoader()}
async function listarPublic(){await ensureTS();showLoader();try{const res=await fetchJSON(API_URL+"/api/episodes");return res.items||[]}finally{hideLoader()}}
function renderEpisodes(list){const c=document.getElementById("list");c.innerHTML="";const f=document.createDocumentFragment();list.forEach(ep=>{const n=ep.episodio??ep.id;const t=ep.titulo??ep.title??"";const row=document.createElement("div");row.className="episodeRow";row.dataset.episodio=String(n);row.innerHTML=`<span>#${n} - ${t}</span><div class="actions"><button class="editBtn">Editar</button><button class="delBtn">Eliminar</button></div>`;f.appendChild(row)});c.appendChild(f)}
async function refreshList(){const items=await listarPublic();renderEpisodes(items)}
function readForm(){const n=parseInt(document.getElementById("epNum").value,10);return{episodio:isNaN(n)?undefined:n,titulo:document.getElementById("epTitle").value||"",fecha:document.getElementById("epDate").value||"",embed:document.getElementById("epEmbed").value||"",dl1080:document.getElementById("epDl1080").value||"",dl720:document.getElementById("epDl720").value||"",dl480:document.getElementById("epDl480").value||""}}
function writeForm(ep){document.getElementById("epNum").value=ep.episodio??ep.id??"";document.getElementById("epTitle").value=ep.titulo??ep.title??"";document.getElementById("epDate").value=ep.fecha??"";document.getElementById("epEmbed").value=ep.embed??"";document.getElementById("epDl1080").value=ep.dl1080??"";document.getElementById("epDl720").value=ep.dl720??"";document.getElementById("epDl480").value=ep.dl480??""}
async function loadToForm(epn){const id=Number(epn);if(!id)return;const items=await listarPublic();const ep=items.find(x=>(x.episodio??x.id)===id);if(ep)writeForm(ep)}
async function addOrUpdate(e){e.preventDefault();if(!ADMIN_TOKEN)return;const p=readForm();if(!p.episodio||!p.titulo||!p.fecha||!p.embed)return;showLoader();try{const id=p.episodio;try{await fetchJSON(API_URL+"/api/admin/episodes/"+id,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)})}catch{await fetchJSON(API_URL+"/api/admin/episodes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)})}await refreshList()}finally{hideLoader();document.getElementById("formAdd").reset()}}
async function delEpisode(epn){if(!ADMIN_TOKEN)return;const id=parseInt(epn,10);if(!id||isNaN(id))return;showLoader();try{await fetchJSON(API_URL+"/api/admin/episodes/"+id,{method:"DELETE"});await refreshList()}finally{hideLoader()}}
document.addEventListener("DOMContentLoaded",()=>{loadToken();const bL=document.getElementById("btnLogin");if(bL)bL.addEventListener("click",login);const bO=document.getElementById("btnLogout");if(bO)bO.addEventListener("click",logout);const f=document.getElementById("formAdd");if(f)f.addEventListener("submit",addOrUpdate);const list=document.getElementById("list");if(list){list.addEventListener("click",e=>{const btn=e.target.closest("button");if(!btn)return;const row=btn.closest(".episodeRow");const epn=row?row.dataset.episodio:null;if(btn.classList.contains("delBtn"))delEpisode(epn);else if(btn.classList.contains("editBtn"))loadToForm(epn)})}if(ADMIN_TOKEN)refreshList()});
